---
- name: Configureer beide VM's
  hosts: all
  become: true

  roles:
    - docker_install
    - user_setup

- name: Run Hello World container op Azure
  hosts: azure
  become: true
  tasks:
    - name: Start Hello World container
      docker_container:
        name: hello_container
        image: hello-world
        state: started
