name: Manual Destroy Infra

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform destroy
        run: cd terraform && terraform destroy -auto-approve
